- name: Setup Packages
  hosts: kibana_instances
  become: true
  tasks:
  - name: verify kibana is on the latest version
    ansible.builtin.apt:
      name: "kibana"
      state: latest

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts["default_ipv4"]["address"]

  - name: copy config file
    ansible.builtin.template:
      src: ./configs/kibana.yml.j2
      dest: /etc/kibana/kibana.yml

  - name: set config permissions
    ansible.builtin.file:
      path: /etc/kibana/kibana.yml
      owner: kibana
      group: kibana
      mode: '0644'

  - name: reload systemd services
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      name: kibana

  - name: Allow udp ports for nomad
    community.general.ufw:
      rule: allow
      port: '5601'
      proto: tcp
      state: reloaded

