- name: Setup Packages
  hosts: elastic_instances
  become: true
  tasks:
  - name: verify elasticsearch is on the latest version
    ansible.builtin.apt:
      name: "elasticsearch"
      state: latest

  - name: Allow udp ports for nomad
    community.general.ufw:
      rule: allow
      port: '9200'
      proto: tcp

  - name: Allow udp ports for nomad
    community.general.ufw:
      rule: allow
      port: '9300'
      proto: tcp
      state: reloaded

  - name: copy config file
    ansible.builtin.template:
      src: ./configs/elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml


  - name: fix permissions of config file
    ansible.builtin.file:
      path: /etc/elasticsearch/elasticsearch.yml
      owner: elasticsearch
      group: elasticsearch
      mode: '0644'

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /usr/share/elasticsearch
      state: directory
      mode: '0744'
      owner: elasticsearch
      group: elasticsearch
    loop:
      - /var/log/elasticsearch
      - /usr/share/elasticsearch
      - /usr/share/elasticsearch/logs

  - name: reload systemd services
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: remove ssl
    ansible.builtin.command:
      cmd: "/usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.http.ssl.keystore.secure_password"
    ignore_errors: true

  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: restarted
      enabled: true
      name: elasticsearch



