- name: Add apt repo
  hosts: cluster
  become: true
  tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: [net-tools,gpg]
        state: latest

    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        validate_certs: true

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes