- name: Setup Packages
  hosts: nomad_instances
  become: true
  tasks:
  - name: Update nomad is on the latest version
    ansible.builtin.apt:
      name: "nomad"
      state: latest

  - name: Allow udp ports for nomad
    community.general.ufw:
      rule: allow
      port: '4648'
      proto: udp
      state: reloaded

  - name: copy service file
    ansible.builtin.copy:
      src: ./configs/nomad.service
      dest: /etc/systemd/system/nomad.service
      owner: root
      group: root
      mode: '0644'

  - name: reload systemd services
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      name: nomad

  - name: Allow all access to tcp port 4646:4648
    community.general.ufw:
      rule: allow
      port: 4646:4648
      proto: tcp

  - ansible.builtin.command:
      cmd: nomad server join 192.168.1.249:4648

