
- name: Setup Packages
  hosts: vault_instances
  become: true
  tasks:
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "vault"
      state: latest

  - name: reload systemd services
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      name: vault

  - name: Allow tcp ports vault
    community.general.ufw:
      rule: allow
      port: '8300'
      proto: tcp
      state: reloaded
